name: an_app_vone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  webview_flutter: ^3.0.4
  json_annotation: ^4.6.0
  http: ^0.13.5
  provider: any
  flutter_spinkit: ^5.1.0
  # firebase_core: 1.24.0
  firebase_core: ^2.4.0
  # firebase_auth: 3.11.2
  firebase_auth: ^4.2.3
  flutter: 
    sdk: flutter
  pull_to_refresh: ^2.0.0
  flutter_html: ^3.0.0-alpha.6

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/images/

resources:
  - string.dart
  - color.dart
#  -\app_styles.dart  (store all styles i.e. material dark, light, cupertino etc.)
#  -\app_dimens.dart  (store all dimension constants)
#
#  -\components (parent component directory)
#  -\your_custom_widget.dart(create custom component here)
#  -\.....
#
#  -\views
#  -\your_view.dart(your view where you import custom component)